# Generated by Django 5.1.7 on 2025-03-29 20:33

import django_ckeditor_5.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Course Enrollment",
                "verbose_name_plural": "Course Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Course Lesson",
                "verbose_name_plural": "Course Lessons",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Archived", "Archived")],
                default="Active",
                help_text="Set the course status.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Upload a thumbnail image for the course.",
                null=True,
                upload_to="course_thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="attachments",
            field=models.FileField(
                blank=True,
                help_text="Upload additional lesson materials.",
                null=True,
                upload_to="lesson_attachments/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a lesson video (if available).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the assignment was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(
                help_text="Specify the due date and time for this assignment.",
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Provide detailed instructions for completing the assignment.",
                verbose_name="Assignment Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="lesson",
            field=models.ForeignKey(
                help_text="Select the lesson this assignment belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.lesson",
                verbose_name="Lesson",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Set the maximum score a student can achieve in this assignment.",
                verbose_name="Maximum Score",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(
                help_text="Enter the assignment title (max 255 characters).",
                max_length=255,
                verbose_name="Assignment Title",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the course was created.",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(help_text="Provide a detailed course description."),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                help_text="Select the instructor for this course. Only admins and instructors are allowed.",
                limit_choices_to={"role__in": ["admin", "instructor"]},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instructor",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                help_text="Specify the course language. Default is Arabic.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Enter the course title (max 255 characters).",
                max_length=255,
                verbose_name="Course Title",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the student has completed the course.",
                verbose_name="Completed",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                help_text="Choose the course for enrollment.",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the student enrolled in the course.",
                verbose_name="Enrollment Date",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="progress",
            field=models.FloatField(
                default=0.0,
                help_text="Track the student's progress as a percentage (0.0 - 100.0).",
                verbose_name="Course Progress",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Select the student enrolling in this course.",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enrolled Student",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Provide the lesson content. You can use formatted text if supported.",
                verbose_name="Lesson Content",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Select the course this lesson belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the lesson was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="instructor",
            field=models.ForeignKey(
                help_text="Choose the instructor responsible for this lesson.",
                limit_choices_to={"role__in": ["admin", "instructor"]},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instructor",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Define the lesson order within the course.",
                verbose_name="Lesson Order",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Enter the lesson title (max 255 characters).",
                max_length=255,
                verbose_name="Lesson Title",
            ),
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
