# Generated by Django 5.1.7 on 2025-04-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_assignment_options_alter_enrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('3_days', '3 Days'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('4_weeks', '4 Weeks'), ('8_weeks', '8 Weeks'), ('12_weeks', '12 Weeks')], default='', help_text='Select the total duration of the course (e.g., 1 Day, 1 Week, 4 Weeks).', max_length=10, verbose_name='Course Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='learning_points',
            field=models.TextField(default='', help_text='Enter key learning points separated by semicolons (;). Example: Learn Python basics; Understand OOP; Work with Django', verbose_name='Learning Points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Select the difficulty level of the course.', max_length=15, verbose_name='Course Level'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(choices=[('5_min', '5 Minutes'), ('10_min', '10 Minutes'), ('15_min', '15 Minutes'), ('30_min', '30 Minutes'), ('45_min', '45 Minutes'), ('1_hour', '1 Hour'), ('1.5_hours', '1.5 Hours'), ('2_hours', '2 Hours')], default='', help_text='Select the estimated duration of the lesson (e.g., 10 Minutes, 30 Minutes, 1 Hour).', max_length=10, verbose_name='Lesson Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Select the category this course belongs to (e.g., JavaScript, React, Python, Flutter, Node, Unity).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory', verbose_name='Course Category'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
