# Generated by Django 5.1.7 on 2025-04-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
    ]
