# Generated by Django 5.1.7 on 2025-04-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_options_remove_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='introduction',
            field=models.TextField(default='', verbose_name='Lesson Introduction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.OneToOneField(help_text='Select the lesson this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.lesson', verbose_name='Lesson'),
        ),
    ]
