# Generated by Django 5.1.7 on 2025-04-07 17:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='started_at',
            new_name='answered_at',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='completed',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Provide a brief description of the quiz (optional).', null=True, verbose_name='Quiz Description'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
